---
- name: Destroy environment on AWS
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
    AWS_DEFAULT_REGION: "{{ aws_region_final | default(aws_region) }}"
  tasks:
  - name: Get facts for cloudformation stack
    amazon.aws.cloudformation_info:
      stack_name: "{{ project_tag }}"
    register: r_stack_facts

  - name: Grab and set stack creation time
    when: project_tag in r_stack_facts.cloudformation
    vars:
      _stack_description: "{{ r_stack_facts.cloudformation[project_tag].stack_description }}"
    ansible.builtin.set_fact:
      stack_creation_time: >-
        {{ _stack_description.creation_time | default(_stack_description.CreationTime) }}
      stack_status: >-
        {{ _stack_description.stack_status | default(_stack_description.StackStatus) }}

  - name: Run infra_aws_create_inventory role
    ansible.builtin.include_role:
      name: infra_aws_create_inventory

  - name: Create local ssh provision facts (key already exists)
    when: ssh_provision_key_name is undefined
    ansible.builtin.include_role:
      name: create_ssh_provision_key

  - name: SSH config setup
    when:
    - groups["bastions"] is defined
    - groups["bastions"] | length > 0
    ansible.builtin.include_role:
      name: infra_common_ssh_config_generate

- name: Set ssh extra args for all hosts, use ssh_config just created
  hosts: all
  gather_facts: false
  any_errors_fatal: true
  ignore_errors: false
  tasks:
  - name: Add -F option ansible_ssh_extra_args
    ansible.builtin.set_fact:
      ansible_ssh_extra_args: "{{ ansible_ssh_extra_args | default() }} -F {{ hostvars.localhost.ansible_ssh_config }}"

- name: Start all AWS instances if they are stopped
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  environment:
    AWS_ACCESS_KEY_ID: "{{aws_access_key_id}}"
    AWS_SECRET_ACCESS_KEY: "{{aws_secret_access_key}}"
    AWS_DEFAULT_REGION: "{{aws_region_final|d(aws_region)}}"
  tasks:
  - ansible.builtin.include_tasks: aws_instances_start.yaml

# Call Remove Workloads for workloads that need to clean up "other" infrastructure
# that was not created on the cluster (e.g. VMware virtual machines)
- name: Remove workloads
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
  - name: Remove workloads
    when: remove_workloads | default("") | length > 0
    ansible.builtin.include_role:
      name: "{{ workload_loop_var }}"
    vars:
      ACTION: "remove"
    loop: "{{ remove_workloads }}"
    loop_control:
      loop_var: workload_loop_var

- name: Have the OpenShift installer cleanup what it did
  hosts: bastions
  gather_facts: false
  become: false
  tasks:
  - name: Wait for the bastion host to be available
    ansible.builtin.wait_for_connection:
      timeout: 60
    register: bwait
    ignore_errors: true

  - name: Ensure old AWS credentials are absent
    ansible.builtin.file:
      state: absent
      path: "/home/{{ ansible_user }}/.aws/credentials"

  - name: Add AWS credentials for sandboxes
    when:
    - hostvars.localhost.student_access_key_id | default("") | length > 0
    - hostvars.localhost.student_access_secret_key | default("") | length > 0
    ansible.builtin.blockinfile:
      path: "/home/{{ ansible_user }}/.aws/credentials"
      create: true
      insertbefore: BOF
      marker: "# {mark} ANSIBLE MANAGED BLOCK Student Credentials"
      block: |-
        [default]
        aws_access_key_id = {{ hostvars.localhost.student_access_key_id }}
        aws_secret_access_key = {{ hostvars.localhost.student_secret_access_key }}

  # Use shared account when no sandbox account has been configured
  - name: Add AWS credentials for shared account
    when:
    - hostvars.localhost.student_access_key_id | default("") | length == 0
    - aws_access_key_id | default("") != ""
    - aws_secret_access_key | default("") != ""
    ansible.builtin.blockinfile:
      state: present
      path: "/home/{{ ansible_user }}/.aws/credentials"
      create: true
      insertbefore: BOF
      marker: "# {mark} ANSIBLE MANAGED BLOCK Default Credentials"
      block: |-
        [default]
        aws_access_key_id = {{ aws_access_key_id }}
        aws_secret_access_key = {{ aws_secret_access_key }}

  - name: Call role to destroy the OpenShift cluster
    when: bwait is successful
    ansible.builtin.include_role:
      name: host_ocp4_destroy

- name: Import default cloud provider destroy playbook
  ansible.builtin.import_playbook: "../../cloud_providers/{{ cloud_provider }}/{{ cloud_provider }}_destroy_env.yml"
