---
# Post Start actions for OCP 4 Cluster configs
- name: Build inventory
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
  - name: Set facts for ssh provision SSH key
    when:
    - ssh_provision_key_name is undefined
    - cloud_provider == 'azure'
    ansible.builtin.include_role:
      name: create_ssh_provision_key

  - name: Locate environment SSH key
    when: cloud_provider == 'azure'
    ansible.builtin.include_role:
      name: locate_env_authorized_key

  - name: Run infra_aws_create_inventory role
    when: cloud_provider == 'aws'
    ansible.builtin.include_role:
      name: infra_aws_create_inventory

  - name: Azure post start actions
    when: cloud_provider == 'azure'
    ansible.builtin.include_role:
      name: infra_azure_create_inventory

  - name: Run infra_openshift_cnv_create_inventory role
    when: cloud_provider == 'openshift_cnv'
    ansible.builtin.include_role:
      name: infra_openshift_cnv_create_inventory

- name: Set ansible_ssh_extra_args
  hosts:
  - all:!windows:!network
  gather_facts: false
  any_errors_fatal: true
  ignore_errors: false
  tasks:
  - name: Set facts for remote access
    ansible.builtin.set_fact:
      ansible_ssh_extra_args: >-
        {{ ansible_ssh_extra_args | default() }}
        -F {{ hostvars.localhost.output_dir }}/{{ config }}_{{ guid }}_ssh_conf

- name: Run recover cluster actions
  hosts: bastions
  run_once: true
  become: false
  gather_facts: false
  tasks:
  - name: Set Ansible Python interpreter to k8s virtualenv
    ansible.builtin.set_fact:
      ansible_python_interpreter: /opt/virtualenvs/k8s/bin/python

  - name: Perform actions on start
    when: ACTION == 'start'
    block:
    - name: Test the bastion host is available, if not skip approve csr and pod cleanup
      ansible.builtin.wait_for_connection:
        timeout: 60
      register: r_wait
      ignore_errors: true

    - name: Approve CertificateSigningRequests
      when: r_wait is successful
      ansible.builtin.include_role:
        name: ocp4_approve_certificate_signing_requests
