---
- name: Step 000 - Pre Infrastructure
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:
  - name: Print debug message
    ansible.builtin.debug:
      msg: "Step 000 Pre Infrastructure"

  - name: Ensure variables are set
    ansible.builtin.assert:
      that: ocp4_pull_secret | default("") | length > 0
      fail_msg: ocp4_pull_secret variable must be defined
      success_msg: ocp4_pull_secret variable is defined
      quiet: true

  - name: AWS Pre Infrastructure tasks
    when: cloud_provider == "aws"
    block:
    # Find and set the AWS Availability Zones using on-demand capacity reservations
    - name: Run infra-aws-capacity-reservation
      vars:
        ACTION: "provision"
      ansible.builtin.include_role:
        name: infra_aws_capacity_reservation

    - name: Set availability zones for Cloudformation and install-config.yml
      when: agnosticd_aws_capacity_reservation_results.reservations | default({}) | length > 0
      block:
      - name: Set availability zone for bastion, masters and workers
        vars:
          _r: "{{ agnosticd_aws_capacity_reservation_results.reservations }}"
        ansible.builtin.set_fact:
          # Cloudformation (bastion)
          aws_availability_zone: "{{ _r.az1.availability_zone }}"
          # Control Plane
          # Support several logical mapping (masters, masters1-3)
          openshift_controlplane_aws_zones_odcr: >-
            {{ [
              _r.masters.availability_zone | default(none),
              _r.masters1.availability_zone | default(none),
              _r.masters2.availability_zone | default(none),
              _r.masters3.availability_zone | default(none),
            ] | select() | list }}
          # workers
          # Support up to 4 zones
          openshift_machineset_aws_zones_odcr: >-
            {{ [
              _r.workers.availability_zone | default(none),
              _r.workers1.availability_zone | default(none),
              _r.workers2.availability_zone | default(none),
              _r.workers3.availability_zone | default(none),
              _r.workers4.availability_zone | default(none),
            ] | select() | list }}

  - name: GCP Pre Infrastructure tasks
    when: cloud_provider == 'gcp'
    block:
    - name: Run add user to GCP project role
      ansible.builtin.include_role:
        name: open_env_gcp_add_user_to_project

    - name: Create GCP Credentials File
      ansible.builtin.include_role:
        name: infra_gcp_credentials_file

    - name: Get Google Cloud SDK
      ansible.builtin.include_role:
        name: infra_gcp_install_sdk

  - name: Azure Pre Infrastructure tasks (generate Windows password if not defined)
    when:
    - cloud_provider == "azure"
    - windows_password is not defined
    ansible.builtin.set_fact:
      generated_windows_password: >-
        {{ lookup('password', '/dev/null chars=ascii_letters,digits '
            ~ 'length=25'
        ) }}
