---
- name: Import detect region tasks
  ansible.builtin.import_tasks: aws_detect_region_tasks.yml

- name: Destroy cloudformation template
  when: cloud_provider == 'aws'
  amazon.aws.cloudformation:
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
    stack_name: "{{ project_tag }}"
    state: "absent"
    region: "{{ aws_region_final | default(aws_region) }}"
    disable_rollback: false
    tags:
      Stack: "project {{ config }}-{{ guid }}"
  register: cloudformation_result
  until: cloudformation_result is succeeded
  retries: "{{ cloudformation_retries | default(3) }}"
  delay: "{{ cloudformation_retry_delay | default(60) }}"
  ignore_errors: true

- name: Report Cloudformation error
  when:
  - not cloudformation_result is succeeded
  - cloud_provider == 'aws'
  - not cloudformation_destroy_ignore_failure
  ansible.builtin.fail:
    msg: "FAIL {{ project_tag }} Destroy Cloudformation"
